//LOGIN
export const USER_LOGIN_REQ = " USER_LOGIN_REQ";
export const USER_LOGIN_SUCCESSFUL = "USER_LOGIN_SUCCESSFUL";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGOUT = " USER_LOGOUT";
//SIGNUP
export const USER_SIGNUP_REQ = "USER_SIGNUP_REQ";
export const USER_SIGNUP_SUCCESSFUL = "USER_SIGNUP_SUCCESSFUL";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";
